import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Header } from "../components/Header";
import "./globals.css";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${roboto.className} min-h-screen bg-gray-100`}>
        <div className="flex flex-col justify-center items-center container mx-auto px-6 py-4">
          <Header />

          <main className="flex justify-center w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
