import { Toaster } from "@/components/ui/toaster";
import ReactQueryProvider from "@/providers/react-query";
import {
  HydrationBoundary,
  QueryClient,
  dehydrate,
} from "@tanstack/react-query";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Header } from "../components/Header";
import "./globals.css";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryKey: ["gifts"],
    queryFn: async () => {
      const response = await fetch(`http://localhost:3000/api/presentes`);
      const data = await response.json();
      return data;
    },
  });

  return (
    <html lang="pt-br">
      <body className={`${roboto.className} min-h-screen bg-gray-100`}>
        <ReactQueryProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <div className="flex flex-col justify-center items-center container mx-auto px-6 py-4">
              <Header />

              <main className="flex justify-center w-full">{children}</main>
            </div>
            <Toaster />
          </HydrationBoundary>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
